#!/bin/bash
set -e

echo "Deploying Blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying Green version..."
kubectl apply -f green_deployment.yaml

echo "Checking logs of Green pods..."
kubectl get pods -l app=django,version=green
GREEN_POD=$(kubectl get pods -l app=django,version=green -o jsonpath='{.items[0].metadata.name}')

kubectl logs $GREEN_POD

echo "Switching Service to Green..."
kubectl apply -f kubeservice.yaml

echo "Done. Traffic is now routed to Green."

