version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: messaging_db
      MYSQL_DATABASE: messaging_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: messaging_db
      MYSQL_DATABASE: messaging_db
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:

